export const CONNECT_WALLET = 'CONNECT_WALLET';
export const CONNECT_GUEST = 'CONNECT_GUEST';
export const DISCONNECT_WALLET = 'DISCONNECT_WALLET';
export const LOAD_CONTRACT = 'LOAD_CONTRACT';
export const CREATE_NFT = 'CREATE_NFT';
export const FETCH_ALL_NFTS = 'FETCH_ALL_NFTS';
export const FETCH_SINGLE_NFT = 'FETCH_SINGLE_NFT';
export const ERROR = 'ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//THIS IS FOR AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const MESSAGE = 'MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const SET_LOADING = 'SET_LOADING';
